### ISSUE TITLE
When passing a redis uri following occurs, Error: Panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by GravyPouch** [inngest/inngest#1916]
**Describe the bug**
When passing a redis uri following occurs, "Error: Panic: runtime error: invalid memory address or nil pointer dereference"

**To Reproduce**
1. Set ENV variable INNGEST_REDIS_URI = redis://red-cscm52jqf0us73eon650:6379
2. Start docker image

**Expected behavior**
Binding to the redis uri and continuing boot.

**Screenshots / Stack trace dump**
<img width="1631" alt="image" src="https://github.com/user-attachments/assets/b0ef2cbe-6d14-456b-a6cc-b7cd0c11c629">

**System info**
- Docker Hash: 28319b799a77
- OS: Linux
- Version 28319b799a77

**Additional context**
Seems to be an issue with how go is handling the URI:
[https://github.com/redis/go-redis/issues/864](https://github.com/redis/go-redis/issues/864)

**Comment by horlaarsco** [comment]
I am getting this error, too. At first, I was getting too many colons when I passed my username and password, but when I switched to passwordless Redis instance, I started to get this.

**Comment by GravyPouch** [comment]
Also had the exact same error when passing username:password

**Comment by journeyWorker** [comment]
I'm not a go developer so I don't know exactly how to do it, but from the code below it looks like it need to parseUrl instead of directly use InitAddress.
I hope someone can fix it quickly.
- https://github.com/inngest/inngest/blob/65d2aeceb1e0f5fbf145c7167161dad41eba74a9/pkg/lite/lite.go#L446

see
- https://github.com/redis/rueidis/tree/bf8de44ea8f1481e7e3b0035cbb471d69294d2ee?tab=readme-ov-file#redis-url
- https://github.com/redis/rueidis/blob/bf8de44ea8f1481e7e3b0035cbb471d69294d2ee/url.go#L20

**Comment by marlon360** [comment]
Fixed with #1965

**Comment by djfarrelly** [comment]
If this wasn't fixed with #1965, it should be fixed in the latest release: https://github.com/inngest/inngest/releases/tag/v1.3.3

Please let us know if it doesn't!
