### ISSUE TITLE
Docker Compose Self Hosting is missing

### ISSUE THREAD

**Issue by flobaader** [inngest/inngest#319]
**Is your feature request related to a problem? Please describe.**
No docker compose file is provided for self hosting, so without an AWS account is difficult to try it out. In the docs it is mentioned, but not implemented in the repository. 

<img width="886" alt="image" src="https://user-images.githubusercontent.com/16624361/208226299-158584a4-d39b-481e-bf2c-294a86608a7e.png">

**Describe the solution you'd like**
To enable us to quickly test the platform, a docker compose config would be awesome. It would be a big plus if the required AWS components are replaced with other open source components, e.g. a Redis Queue for the required cloud components.

I know that this is not an high availability approach, but for us it would be perfect until we need the high availability - then we would go to your could service.

**Additional context**

**Comment by tonyhb** [comment]
This is totally fair.  While we love FDB, we've also invested in time to make sure that this can run solely on eg. Redis, so we should definitely provide a compose file for the platform that can leverage redis, NATS, and our infra.

I'll keep you updated as we add this — it's probably more beneficial than our TF for AWS stacks.  We'll start next week :)

**Comment by flobaader** [comment]
Very nice, so far I have to say that I am very impressed with the product! It has been a little be difficult how to get from the "Getting Started" to "production", because everything is automatically linked and configured e.g. with NODE_ENV.

I hear to search a bit around until I found out, that you just need to set the signing key env and the ingest env.

**Comment by flobaader** [comment]
And @tonyhb it would be awesome id you keep me updated then I can test it out and give some feedback to the documentation! Cheers

**Comment by flobaader** [comment]
@tonyhb any updates on this self hosting topic? :)

**Comment by djfarrelly** [comment]
Documentation on self-hosting can be found on our docs site here: https://www.inngest.com/docs/self-hosting

**Comment by maelp** [comment]
![Image](https://github.com/user-attachments/assets/4a1d7fbd-3362-44b5-a308-246e739745ad)

**Comment by djfarrelly** [comment]
Hi all - this issue was created when pre-1.0 Inngest had a different architecture that we changed and removed from the repo as it was no longer valid as of 1.x. We've added a new Docker compose file and are working on better docs including best practices for health checks, replication, memory, data retention and more. Here is the new compose file in our docs: 

https://www.inngest.com/docs/self-hosting#docker-compose-example

**Comment by nikosdouvlis** [comment]
> Hi all - this issue was created when pre-1.0 Inngest had a different architecture that we changed and removed from the repo as it was no longer valid as of 1.x. We've added a new Docker compose file and are working on better docs including best practices for health checks, replication, memory, data retention and more. Here is the new compose file in our docs:
> 
> https://www.inngest.com/docs/self-hosting#docker-compose-example

Hi @djfarrelly - thanks for this. I tested the compose file and it works as expected with no changes required. I ended up sticking with SQLite for now and I'd noticed that main.db increases in size quickly. 

i scheduled and completed the workflow shown below 500 times
```ts
const studentCreated = inngestClient.createFunction(
  { id: 'student-created' }, //
  { event: 'students/student.created' },
  async ({ event, step }) => {
    await step.sleep('sleep-1', '5s');
    await step.waitForEvent('wait-for-approval', {
      event: 'students/documents.approved',
      timeout: '1d',
    });
    return { message: `Hello ${event.data.name}` };
  },
);
```
 and SQLite climbed to ~20MB in size.
```sh
# ls -all 
total 19056
drwxr-xr-x 1 root root       14 Jul 14 12:01 .
drwxr-xr-x 1 root root       36 Jul 14 12:00 ..
-rw-r--r-- 1 root root 19488768 Jul 14 12:01 main.db
```

All that to say that guidelines regarding data retention would be much appreciated! This is an amazing project so I'd be happy to share any feedback/details needed if that helps shape the docs :)

PS: I'm using SQLite because the PG adapter throws a `fatal, sorry too many clients` error when using `inngest/inngest:v1.8.2` but I'll open a separate issue for that.
